# Generated by Django 6.0.6 on 2026-07-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Normal', 'Normal'), ('Event', 'Event')], max_length=20)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='food/')),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
